// Turn results/<backend>.json files into data.js (window.TLAPS_DATA).
// Deterministic and total: same inputs -> same output; anything suspicious -> throw.
// All validation lives here so the UI can assume complete, trustworthy data.
//
//   node scripts/build-data.mjs
//
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { SITE } from "./site-content.mjs";

const MODES = ["proof-completion", "proof-from-scratch"];

// Canonical manifest: per-source totals [proof-completion, proof-from-scratch].
// Update only when the benchmark version changes.
const CANONICAL = {
  "tlaplus/Examples": [379, 126],
  "TLAPS distribution examples": [103, 57],
  "ZooKeeper (Remix)": [0, 18],
  "Ivy liveness": [0, 12],
  "etcd (Specula)": [0, 8],
  "AbstractRaft": [0, 4],
  "OpenAddressing (lemmy/Examples)": [1, 5],
  "Anvil": [0, 1],
};
const RECORDS = 714;

// The one hand-maintained table: display info per backend id.
const BACKEND_INFO = {
  copilot: { name: "GitHub Copilot", subname: "Copilot agent", org: "GitHub", logo: null, kind: "agent" },
  codex: { name: "OpenAI Codex", subname: "Codex agent (gpt-5.5)", org: "OpenAI", logo: null, kind: "agent" },
};

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const r1 = (x) => Math.round(x * 10) / 10;

const models = readdirSync("results").filter((f) => f.endsWith(".json")).map((f) => {
  const { meta, results } = JSON.parse(readFileSync(`results/${f}`, "utf8"));

  // ---- validate: recompute from results[], check against canon and meta ----
  if (results.length !== RECORDS) throw new Error(`${f}: ${results.length} records != ${RECORDS}`);
  const byMode = {}, bySource = {};
  for (const r of results) {
    if (!["PASS", "FAIL", "CHEATING"].includes(r.check_verdict))
      throw new Error(`${f}: ${r.benchmark} [${r.mode}] has infra verdict ${r.check_verdict} - re-run before publishing`);
    if (!CANONICAL[r.source]) throw new Error(`${f}: unknown source "${r.source}"`);
    const m = (byMode[r.mode] ??= { total: 0, PASS: 0, CHEATING: 0 });
    m.total++; m[r.check_verdict] = (m[r.check_verdict] ?? 0) + 1;
    const s = (bySource[r.source] ??= { pass: 0, fail: 0, cheat: 0, total: 0, perMode: {} });
    s.total++;
    if (r.check_verdict === "PASS") s.pass++;
    else if (r.check_verdict === "CHEATING") s.cheat++;
    else s.fail++;
    s.perMode[r.mode] = (s.perMode[r.mode] ?? 0) + 1;
  }
  for (const [src, [pc, pfs]] of Object.entries(CANONICAL)) {
    const got = bySource[src]?.perMode ?? {};
    if ((got["proof-completion"] ?? 0) !== pc || (got["proof-from-scratch"] ?? 0) !== pfs)
      throw new Error(`${f}: ${src} counts don't match the canonical manifest`);
  }
  for (const m of MODES) { // cross-check recomputed rates vs the file's own summaries
    const rate = r1((byMode[m].PASS / byMode[m].total) * 100);
    if (Math.abs(rate - meta.summary_by_mode[m].pass_rate) > 0.05)
      throw new Error(`${f}: recomputed ${m} pass_rate ${rate} != meta ${meta.summary_by_mode[m].pass_rate}`);
  }

  // ---- aggregate ----
  const cheat = MODES.reduce((n, m) => n + (byMode[m].CHEATING ?? 0), 0);
  const perTask = Object.fromEntries(Object.entries(bySource).map(([src, s]) =>
    [slug(src), { rate: r1((s.pass / s.total) * 100), pass: s.pass, fail: s.fail, cheat: s.cheat, total: s.total }]));

  const info = BACKEND_INFO[meta.backend] ?? { name: meta.backend, org: "?", logo: null, kind: "base" };
  return {
    id: meta.backend, ...info, generated: meta.generated,
    // Headline = unweighted mean of the two mode pass rates (weights both capabilities equally).
    score: r1(MODES.reduce((n, m) => n + (byMode[m].PASS / byMode[m].total) * 100, 0) / MODES.length),
    perMetric: {
      completion: r1((byMode["proof-completion"].PASS / byMode["proof-completion"].total) * 100),
      scratch: r1((byMode["proof-from-scratch"].PASS / byMode["proof-from-scratch"].total) * 100),
      cheating: r1((cheat / RECORDS) * 100),
    },
    perTask,
  };
});

const data = {
  paper: SITE.paper,
  metrics: [
    { id: "completion", name: "--mode proof-completion",  blurb: "Pass rate on the 483 proof-completion tasks." },
    { id: "scratch",    name: "--mode proof-from-scratch", blurb: "Pass rate on the 231 proof-from-scratch tasks." },
    { id: "cheating",   name: "Cheating", invert: true, blurb: "Share of all 714 tasks the checker flagged as gamed. Lower is better." },
  ],
  // Leaderboard per-source expand: slug ids match perTask keys; n = tasks across both modes.
  tasks: Object.entries(CANONICAL).map(([name, [pc, pfs]]) => ({ id: slug(name), name, n: pc + pfs })),
  models: models.sort((a, b) => b.score - a.score),
  // Preserved page content (Benchmark task-type cards + source cards, Cite).
  modes: SITE.modes,
  sources: SITE.sources,
  coverage: SITE.coverage,
  bibtex: SITE.bibtex,
};

writeFileSync("data.js",
  "// GENERATED by scripts/build-data.mjs - do not edit by hand.\n" +
  "// Leaderboard (metrics/tasks/models) is recomputed from results/*.json;\n" +
  "// page content (paper/modes/sources/bibtex) comes from scripts/site-content.mjs.\n" +
  "window.TLAPS_DATA = " + JSON.stringify(data, null, 2) + ";\n");
console.log(`Wrote data.js: ${models.length} model(s), ${data.tasks.length} sources.`);
